In [1]:
import torch

In [58]:
a=torch.randint(1, 54999, (500,))
b=torch.rand((500,))
a1=torch.randint(1, 54999, (500,))
b1=torch.rand((500,))

def f(a, b, a1, b1, device='cuda'):
    a=a.to(device)
    b=b.to(device)
    a1=a1.to(device)
    b1=b1.to(device)
    v=torch.zeros((55000), device=device)
    v[a] = b
    v1=torch.zeros((55000), device=device)
    v1[a1]=b1
    return torch.inner(v, v1)
f(a, b, a1, b1)
# timeit f(a, b, a1, b1)

def f1(a, b, a1, b1):
    k = {}
    for ia, ib in zip(a, b):
        k[int(ia)] = float(ib)
    v=0
    for ia, ib in zip(a1, b1):
        v += k.get(int(ia), 0)*float(ib)
    return v

In [63]:
def f100(a, b, a1, b1, device='cuda'):
    a=a.to(device)
    b=b.to(device)
    a1=a1.to(device)
    b1=b1.to(device)
    for i in range(100):
        v=torch.zeros((55000), device=device)
        v[a] = b
        v1=torch.zeros((55000), device=device)
        v1[a1]=b1
        r = torch.dot(v, v1)
    return r

In [59]:
f(a, b, a1, b1)

tensor(1.1938, device='cuda:0')

In [65]:
%timeit f100(a, b, a1, b1, 'cpu')

6.14 ms ± 173 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [4]:
%timeit f1(a, b, a1, b1)

1.46 ms ± 4.31 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
109 μs ± 909 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [66]:
%timeit f(a, b, a1, b1, 'cpu')

112 μs ± 847 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [49]:
def f2(a, b, a1, b1, device='cuda'):
    v=torch.zeros((100, 55000), device=device)
    for i in range(a.size()[0]):
        v[i][a[i]] = b[i]
    v1=torch.zeros((100, 55000), device=device)
    for i in range(a1.size()[0]):
        v1[i][a[i]] = b[i]
    return torch.matmul(v.reshape(100,1,55000), v1.reshape(100,55000,1)).squeeze(1)


In [7]:
def create_int(n1, n2=1):
    if n2==1:
        return torch.randint(1, 54999, (n1,), device='cuda')
    else:
        return torch.randint(1, 54999, (n1, n2), device='cuda')

In [8]:
def create_rand(n1, n2=1):
    if n2==1:
        return torch.rand((n1), device='cuda')
    else:
        return torch.rand((n1, n2), device='cuda')

In [9]:
aa=create_int(100, 500)
aa1=create_int(100, 500)
bb=create_rand(100, 500)
bb1=create_rand(100, 500)

In [15]:
v=torch.zeros((100, 55000), device='cuda')

In [16]:
v[0][a[0]]=b[0]

In [14]:
v[0].size()

torch.Size([100])

In [50]:
f2(aa, bb, aa1, bb1)

tensor([[161.0678],
        [162.9776],
        [164.5586],
        [162.5389],
        [162.6674],
        [168.6807],
        [157.1375],
        [171.1461],
        [154.9973],
        [174.8042],
        [162.2551],
        [168.1856],
        [182.1179],
        [178.5443],
        [170.2158],
        [161.8491],
        [158.8582],
        [177.0495],
        [184.2227],
        [182.1853],
        [173.8644],
        [168.2997],
        [172.8974],
        [161.3595],
        [160.5598],
        [155.9152],
        [170.7030],
        [162.1870],
        [165.8971],
        [175.1031],
        [168.5596],
        [175.4227],
        [170.0728],
        [161.0659],
        [169.8368],
        [159.0128],
        [166.7143],
        [171.7919],
        [164.7404],
        [163.6297],
        [165.8949],
        [152.5069],
        [155.8599],
        [166.4060],
        [169.9680],
        [164.6809],
        [163.4969],
        [171.0675],
        [168.9242],
        [166.4174],


In [67]:
%timeit f2(aa, bb, aa1, bb1)

1.65 ms ± 6.98 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [25]:
x=create_rand(3,2)

In [35]:
y=create_rand(3,2)

In [32]:
z=torch.inner(x,y)

In [33]:
z.size()

torch.Size([3, 4])

In [31]:
y=create_rand(4,2)

In [34]:
torch.dot(x,y)

RuntimeError: 1D tensors expected, but got 2D and 2D tensors

In [36]:
torch.dot(x[0], y[0])

tensor(1.0246, device='cuda:0')

In [39]:
torch.mm(x.transpose(0,1),y)

tensor([[1.3986, 1.3617],
        [1.2097, 1.1269]], device='cuda:0')

In [40]:
x.transpose(0,1)

tensor([[0.5963, 0.6798, 0.6079],
        [0.7495, 0.1386, 0.6691]], device='cuda:0')

In [41]:
x.reshape(2,3)

tensor([[0.5963, 0.7495, 0.6798],
        [0.1386, 0.6079, 0.6691]], device='cuda:0')

In [42]:
x

tensor([[0.5963, 0.7495],
        [0.6798, 0.1386],
        [0.6079, 0.6691]], device='cuda:0')

In [43]:
x.transpose(1,0)

tensor([[0.5963, 0.6798, 0.6079],
        [0.7495, 0.1386, 0.6691]], device='cuda:0')

In [44]:
torch.matmul(x,y)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [46]:
torch.matmul(x.reshape(3,1,2),y.reshape(3,2,1))

tensor([[[1.0246]],

        [[0.5487]],

        [[0.9521]]], device='cuda:0')